const fs = require('fs');
const vm = require('vm');
const assert = require('assert');
const handlers = {};
const gradient = { addColorStop() {} };
const methods = new Set(['setTransform','clearRect','beginPath','ellipse','fill','moveTo','quadraticCurveTo','closePath','save','clip','fillRect','restore','stroke','lineTo','fillText']);
const ctx = new Proxy({}, { get(target, key) { if (key === 'createRadialGradient' || key === 'createLinearGradient') return () => gradient; if (methods.has(key)) return () => {}; return target[key]; }, set(target, key, value) { target[key] = value; return true; } });
const playground = { getBoundingClientRect: () => ({ width: 800, height: 600 }), addEventListener: (type, fn) => { handlers[type] = fn; }, setPointerCapture() {} };
const canvas = { getContext: () => ctx };
const generic = { addEventListener() {}, classList: { add() {}, toggle() {} }, setAttribute() {} };
const sandbox = { console, Math, performance, assert, handlers, devicePixelRatio: 1, requestAnimationFrame() {}, setTimeout() {}, window: { addEventListener() {} }, document: { getElementById: id => id === 'slimeCanvas' ? canvas : id === 'playground' ? playground : generic, querySelectorAll: () => [] } };
vm.createContext(sandbox);
const test = `
const initial = restOffsets.map(point => ({ ...point }));
handlers.pointerdown({ pointerId: 1, offsetX: 560, offsetY: 330, preventDefault() {} });
handlers.pointermove({ pointerId: 1, offsetX: 690, offsetY: 250, preventDefault() {} });
for (let i = 0; i < 180; i++) simulate(FIXED_STEP);
handlers.pointerup({ pointerId: 1, offsetX: 690, offsetY: 250 });
const retained = restOffsets.map(point => ({ ...point }));
const deformation = Math.max(...retained.map((point, index) => Math.hypot(point.x - initial[index].x, point.y - initial[index].y)));
assert(deformation > 20, 'dragging must deform the particle shape rather than only scale an ellipse');
for (let i = 0; i < 600; i++) simulate(FIXED_STEP);
const center = centroid();
const drift = Math.max(...points.map((point, index) => Math.hypot(point.x - center.x - retained[index].x, point.y - center.y - retained[index].y)));
assert(drift < 10, 'the gel must settle around its retained material shape');
assert(Math.abs(Math.abs(polygonArea()) - restArea) / restArea < .08, 'pressure must approximately preserve volume');
`;
vm.runInContext(fs.readFileSync('game.js', 'utf8') + test, sandbox);
console.log('soft-body deformation, shape memory, and pressure checks passed');
